---
title: "Criando a meta-base e avaliando"
output:
  html_document:
    df_print: paged
knit: (function(input_file, encoding) { out_dir <- 'docs'; rmarkdown::render(input_file,
  encoding=encoding, output_file=file.path(dirname(input_file), out_dir, 'meta_base.html'))})
---


Carregando e instalando as bibliotecas necessárias:
  
```{r}
if(!require("foreign")) {
  install.packages("foreign")
}

if(!require("devtools")) {
  install.packages("devtools")
}
```

Carregando e instalando o pacote *mfe*:

```{r}
devtools::install_github("rivolli/mfe")
require("mfe")
```

Carregando os algoritmos de classificação:

```{r}
source("kfold.R")
source("classificadores.R")
```

Extraindo as medidas de caracterização tradicionais e rodando diversos classificadores para várias bases de dados:

```{r}
set.seed(1)
files = sample(list.files(pattern=".arff", full.names=TRUE), 30)

aux = lapply(files, function(file) {
  print(file)
  data = read.arff(file)
  medidas = metafeatures(class ~ ., data, summary="mean")
  acc = rowMeans(desempenho(data, cl=c("RF", "SVM")))
  alg = as.numeric(which.max(acc))
  c(medidas, class=alg)
})

aux = do.call("rbind", aux)

# remove NAs
aux[!is.finite(aux)] = 0

aux = data.frame(aux)
aux$class = as.factor(aux$class)
head(aux)
```

Desempenho em predizer o melhor algoritmo:

```{r}
set.seed(1)
data = kfold(aux)
acc = mapply(function(tran, test) {
classificadores(tran, test, cl=c("RF", "SVM"))
}, tran=data$tran, test=data$test)

print(acc)
print(rowMeans(acc))
boxplot(t(acc))
print(summary(aux$class)/30)
```
