---
title: "Extraindo as medidas tradicionais para caracterização"
output:
  html_document:
    df_print: paged
knit: (function(input_file, encoding) { out_dir <- 'docs'; rmarkdown::render(input_file,
  encoding=encoding, output_file=file.path(dirname(input_file), out_dir, 'tradicionais.html'))})
---

Carregando e instalando as bibliotecas necessárias:
  
```{r}
if(!require("foreign")) {
  install.packages("foreign")
}

if(!require("devtools")) {
  install.packages("devtools")
}

require("foreign")
```

Carregando e instalando o pacote *mfe*:

```{r}
devtools::install_github("rivolli/mfe")
require("mfe")
```

Selecionando uma base de dados do OpenML:

```{r}
set.seed(1)
file = sample(list.files(pattern=".arff", full.names=TRUE), 1)
print(file)
```
Extraindo as medidas de caracterização tradicionais para a base:

```{r}
data = read.arff(file)
medidas = metafeatures(class ~ ., data, summary="mean")
print(medidas)
```
Extraindo as medidas de caracterização tradicionais para varias bases de dados:

```{r}
set.seed(1)
files = sample(list.files(pattern=".arff", full.names=TRUE), 10)

aux = lapply(files, function(file) {
  print(file)
  data = read.arff(file)
  medidas = metafeatures(class ~ ., data, summary="mean")
  return(medidas)
})

do.call("rbind", aux)
```
